apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheiner-exemplo-pod
  namespace: java-rabbit
  labels:
    app: scheiner-exemplo-pod
spec:
  selector:
    matchLabels:
      app: scheiner-exemplo-pod
  template:
    metadata:
      labels:
        app: scheiner-exemplo-pod
    spec:
      containers:
      - name: service
        image: lscheiner/scheiner-exemplo-pod:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3               
        ports:
        - containerPort: 8080        

