apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-java-rabbit
  namespace: java-rabbit
  labels:
    app: keda-java-rabbit
spec:
  selector:
    matchLabels:
      app: keda-java-rabbit
  template:
    metadata:
      labels:
        app: keda-java-rabbit
    spec:
      containers:
      - name: service
        image: lscheiner/scheiner-rabbitmq
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      hostAliases:
      - ip: "10.0.1.128"
        hostnames:
        - "rabbitmq.lab.local"           

